import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { ThemeProvider } from "@/components/ui/theme-provider";
import { Toaster } from "@/components/ui/sonner";

import { Navbar } from "./_components/ui/Navbar";
import Footer from "./_components/ui/Footer";
import { convertMarkdown } from "./_lib/convertMarkdown";
import { IdeasContextProvider } from "./_components/IdeasContext";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { ideas } = await convertMarkdown();

  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${inter.variable} h-full antialiased`}
    >
      <body
        suppressHydrationWarning
        className="h-screen w-screen flex flex-col bg-background text-foreground transition-colors"
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar />
          <IdeasContextProvider initialIdeas={ideas}>
            {children}
            <Toaster />
          </IdeasContextProvider>
          <div className="flex-1" /> {/* pushes footer down */}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
