import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "./_components/ui/Navbar";
import Footer from "./_components/ui/Footer";
import { IdeasContextProvider } from "./_components/IdeasContext";
import { convertMarkdown } from "./_lib/convertMarkdown";
import { Toaster } from "sonner";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { ideas } = await convertMarkdown();

  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${inter.variable} h-full antialiased`}
    >
      <body
        suppressHydrationWarning
        className="min-h-screen w-screen flex flex-col bg-background text-foreground transition-colors overflow-x-hidden"
      >
        <IdeasContextProvider initialIdeas={ideas}>
          <Navbar />
          <main className="flex-1">{children}</main>
          <Toaster />
          <Footer />
        </IdeasContextProvider>
        {/* <div className="flex-1" /> pushes footer down */}
      </body>
    </html>
  );
}
